# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6e6d3d356bc25b44d0819d1e503f95800ece98900472fff1e2cbed7159fa11e9ac32ed3ef9c9f92817143e5f73b137861d920e004e0f0d01140d0fe605fe7d

test:
  secret_key_base: 583c09ccf0f745c4ea2abb0db82606b9f4fd4b8b00ab298241b588147d179fe45d88715d093301a35ff8421715df7dafd3517eaaa415f099208382de23858b3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
